  datafile<-"./household_power_consumption.txt"
  data<-read.table(datafile,header = TRUE, sep = ";", stringsAsFactors = FALSE, dec = ".")
  subsetdata<-data[data$Date %in% c("1/2/2007", "2/2/2007"),]
  datetime<-strptime(paste(subsetdata$Date, subsetdata$Time,sep = ""), "%d/%m/%Y %H:%M:%S")
  globalActivePower<-as.numeric(subsetdata$Global_active_power)
  globalReactivePower<-as.numeric(subsetdata$Global_reactive_power)
  voltage<-as.numeric(subsetdata$Voltage)
  submeter_1<-as.numeric(subsetdata$Sub_metering_1)
  submeter_2<-as.numeric(subsetdata$Sub_metering_2)
  submeter_3<-as.numeric(subsetdata$Sub_metering_3)
  png("plot4.png", width = 500,height = 500)
  par(mfrow = c(2,2))
  plot(datetime, globalActivePower, type = "l", xlab = "",ylab = "Global Active Power", cex = 0.2)
  plot(datetime, voltage, type = "l", xlab = "datetime", ylab = "Voltage")
  plot(datetime, submeter_1, type = "l", ylab = "Energy Submitting", xlab = "")
  lines(datetime, submeter_2, type = "l", col = "red")
  lines(datetime, submeter_3, type = "l", col = "blue")
  legend("topright", c("Sub_meter_1","Sub_meter_2","Sub_meter_3"), lty = 1, lwd = 2.5, col = c("black", "red", "blue"), bty = "o")
  plot(datetime, globalReactivePower, type ="l", xlab= "datetime", ylab = "Global_Reactive_power")
  dev.off()
